#pragma once

namespace oklt {
constexpr char OKL_DIRECTIVE_EXPANSION_STAGE[] = "OKL_DIRECTIVE_EXPANSION_STAGE";
constexpr char MACRO_EXPANSION_STAGE[] = "MACRO_EXPANSION_STAGE";
constexpr char OKL_TO_GNU_ATTR_NORMALIZER_STAGE[] = "OKL_TO_GNU_ATTR_NORMALIZER_STAGE";
constexpr char GNU_TO_STD_ATTR_NORMALIZER_STAGE[] = "GNU_TO_STD_ATTR_NORMALIZER_STAGE";
constexpr char TRANSPILATION_STAGE[] = "TRANSPILATION_STAGE";

}  // namespace oklt
